# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(501, 417)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.master_tab = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.master_tab.sizePolicy().hasHeightForWidth())
        self.master_tab.setSizePolicy(sizePolicy)
        self.master_tab.setObjectName("master_tab")
        self.tab_load = QtWidgets.QWidget()
        self.tab_load.setObjectName("tab_load")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_load)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rdb_rachis_yes = QtWidgets.QRadioButton(self.tab_load)
        self.rdb_rachis_yes.setObjectName("rdb_rachis_yes")
        self.gridLayout_2.addWidget(self.rdb_rachis_yes, 1, 1, 1, 1)
        self.rdb_rachis_no = QtWidgets.QRadioButton(self.tab_load)
        self.rdb_rachis_no.setObjectName("rdb_rachis_no")
        self.gridLayout_2.addWidget(self.rdb_rachis_no, 2, 1, 1, 1)
        self.directory = QtWidgets.QLineEdit(self.tab_load)
        self.directory.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.directory.sizePolicy().hasHeightForWidth())
        self.directory.setSizePolicy(sizePolicy)
        self.directory.setObjectName("directory")
        self.gridLayout_2.addWidget(self.directory, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btn_to_csv = QtWidgets.QPushButton(self.tab_load)
        self.btn_to_csv.setObjectName("btn_to_csv")
        self.horizontalLayout_3.addWidget(self.btn_to_csv)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_load)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.btn_find_files = QtWidgets.QPushButton(self.tab_load)
        self.btn_find_files.setObjectName("btn_find_files")
        self.gridLayout_2.addWidget(self.btn_find_files, 0, 0, 1, 1)
        self.btn_load_data = QtWidgets.QPushButton(self.tab_load)
        self.btn_load_data.setObjectName("btn_load_data")
        self.gridLayout_2.addWidget(self.btn_load_data, 3, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.master_tab.addTab(self.tab_load, "")
        self.tab_preprocess = QtWidgets.QWidget()
        self.tab_preprocess.setObjectName("tab_preprocess")
        self.master_tab.addTab(self.tab_preprocess, "")
        self.tab_analysis = QtWidgets.QWidget()
        self.tab_analysis.setObjectName("tab_analysis")
        self.master_tab.addTab(self.tab_analysis, "")
        self.verticalLayout.addWidget(self.master_tab)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.master_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CT-Seed Analyser 3000"))
        self.rdb_rachis_yes.setText(_translate("MainWindow", "Yes"))
        self.rdb_rachis_no.setText(_translate("MainWindow", "No"))
        self.btn_to_csv.setText(_translate("MainWindow", "Download to CSV"))
        self.label.setText(_translate("MainWindow", "Include Rachis data?"))
        self.btn_find_files.setText(_translate("MainWindow", "Find Files"))
        self.btn_load_data.setText(_translate("MainWindow", "Load Data"))
        self.master_tab.setTabText(self.master_tab.indexOf(self.tab_load), _translate("MainWindow", "Load Data"))
        self.master_tab.setTabText(self.master_tab.indexOf(self.tab_preprocess), _translate("MainWindow", "Pre-Processing"))
        self.master_tab.setTabText(self.master_tab.indexOf(self.tab_analysis), _translate("MainWindow", "Analysis"))

